### ISSUE TITLE
Issue with io.js

### ISSUE THREAD

**Issue by speier** [divshot/divshot-cli#159]
deploy isn't working with `io.js 1.3.0`

```
$ divshot push staging
```

```
events.js:217
    ++this._eventsCount;
           ^
TypeError: Cannot assign to read only property '_eventsCount' of #<EventEmitter>
    at EventEmitter.addListener (events.js:217:12)
    at EventEmitter.onEnd (/usr/local/lib/node_modules/divshot-cli/node_modules/divshot-push/lib/status-handler.js:33:14)
    at Command.<anonymous> (/usr/local/lib/node_modules/divshot-cli/lib/commands/push.js:39:16)
    at /usr/local/lib/node_modules/divshot-cli/node_modules/nash/lib/command.js:98:25
    at Function.<anonymous> (/usr/local/lib/node_modules/divshot-cli/node_modules/nash/node_modules/qmap/index.js:52:9)
    at drain (/usr/local/lib/node_modules/divshot-cli/node_modules/nash/node_modules/drainer/index.js:16:28)
    at /usr/local/lib/node_modules/divshot-cli/node_modules/nash/node_modules/drainer/index.js:25:5
    at Function.<anonymous> (/usr/local/lib/node_modules/divshot-cli/index.js:101:3)
    at drain (/usr/local/lib/node_modules/divshot-cli/node_modules/nash/node_modules/drainer/index.js:29:6)
    at /usr/local/lib/node_modules/divshot-cli/node_modules/nash/node_modules/drainer/index.js:25:5
```

it's working nicely with `node.js 0.12.0`

**Comment by scottcorgan** [comment]
@speier does this happen when pushing to any other environment?

**Comment by speier** [comment]
@scottcorgan yes, unfortunately not working with any environment

**Comment by scottcorgan** [comment]
Fixed via https://github.com/divshot/divshot-cli/commit/9abfb5f4adac1cfa5a50cccf765eaf19469fb465

Go ahead and download the latest divshot-cli, `1.10.2`. Thanks for finding this!

**Comment by speier** [comment]
Thanks!
