### ISSUE TITLE
TypeError on divshot pull

### ISSUE THREAD

**Issue by gbrennon** [divshot/divshot-cli#174]
I was trying to pull my staging code from divshot through divshot-cli and got an TyperError.

```
$ divshot pull staging . --app farmo

Pulling current files from staging

_stream_writable.js:239
    throw new TypeError('Unknown encoding: ' + encoding);
    ^

TypeError: Unknown encoding: buffer
    at WriteStream.setDefaultEncoding (_stream_writable.js:239:11)
    at new WriteStream (fs.js:1830:10)
    at Object.fs.createWriteStream (fs.js:1789:10)
    at /home/gbrennon/.nvm/versions/node/v4.2.1/lib/node_modules/divshot-cli/node_modules/writestreamp/lib/index.js:23:23
    at /home/gbrennon/.nvm/versions/node/v4.2.1/lib/node_modules/divshot-cli/node_modules/writestreamp/node_modules/mkdirp/index.js:38:26
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Is someone experiencing this problem?

**Comment by danielnavaa** [comment]
I am experimenting the same issue its relation with the version of node, i am tried use nvm to change a other version but no found

**Comment by patrickfox** [comment]
Having this exact same issue

**Comment by mindmeoh** [comment]
Up!
